defaults:
  - data: audioset
  - optimizer: adamW
  - trainer: default_trainer
  - extractor : ConvFeatureExtractor
  - masker : TimeInverseBlock

model: JEPA
save_dir: /projects/0/prjs1338
seed: 42
ckpt_path: /gpfs/work4/0/prjs1338/saved_models_jepa_denoised/InChannels=1/WithNoise=True/WithRIR=True/SNRl=-5/SNRh=5/CleanRatio=0.0/SR=16000/BatchSize=32/NrSamples=8/NrGPUs=2/ModelSize=base/LR=0.0004/Masking=time-inverse-masker/TargetProb=0.25/TargetLen=10/ContextLen=10/TopK=8/step=12500.ckpt