defaults:
  - data: audioset_denoise
  - optimizer: adamW_denoise
  - trainer: denoise
  - extractor : ConvFeatureExtractor
  - masker : TimeInverseBlock

model: JEPA
save_dir: /projects/0/prjs1338
seed: 42
